import React from 'react';

interface LegalModalProps {
  isOpen: boolean;
  type: 'privacy' | 'terms' | null;
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, type, onClose }) => {
  if (!isOpen || !type) return null;

  const isPrivacy = type === 'privacy';

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="glass-panel"
        style={{
          width: '100%',
          maxWidth: '600px',
          maxHeight: '80vh',
          overflowY: 'auto',
          padding: '2rem',
          border: '1px solid var(--border-glow)',
          boxShadow: '0 0 50px rgba(124, 108, 255, 0.2)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '0.75rem' }}>
          <h3 style={{ color: 'var(--text-primary)', fontSize: '1.2rem', fontFamily: 'var(--font-display)', fontWeight: 700 }}>
            {isPrivacy ? 'Privacy Policy & Local Privacy Guarantee' : 'Terms & Conditions of Service'}
          </h3>
          <button
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '1.2rem', cursor: 'pointer' }}
          >
            ✕
          </button>
        </div>

        <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: '1.6', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          {isPrivacy ? (
            <>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>1. Local-First Execution Guarantee</h4>
              <p>
                DataMind operates strictly under a local-first paradigm. All dataset ingestion, DuckDB analytical indexing, statistical profiling, and AI model inference (via local Ollama / Qwen models) are processed entirely on your local device.
              </p>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>2. Zero Telemetry & Cloud Exfiltration</h4>
              <p>
                Your raw tabular data, column schemas, and generated SQL queries are never uploaded, stored, or transmitted to any external third-party server or cloud endpoint.
              </p>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>3. AST Security Boundaries</h4>
              <p>
                All SQL queries generated by AI natural-language parsing are passed through a strict Abstract Syntax Tree (AST) validator. Write queries (INSERT, UPDATE, DELETE, DROP) and file-system read functions are deterministically blocked.
              </p>
            </>
          ) : (
            <>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>1. Acceptance of Terms</h4>
              <p>
                By accessing or using DataMind AI Systems, you agree to be bound by these terms. DataMind is provided as an analytical instrument for enterprise and personal data discovery.
              </p>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>2. User Responsibility</h4>
              <p>
                Users are solely responsible for verifying the correctness of AI-generated SQL queries and statistical insights before making critical business or financial decisions based on evidence table outputs.
              </p>
              <h4 style={{ color: 'var(--text-primary)', fontSize: '1rem' }}>3. License & Local Intellectual Property</h4>
              <p>
                All data, indexes, and analytical workspace artifacts generated within DataMind remain the sole property of the local system user.
              </p>
            </>
          )}
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid var(--border-subtle)' }}>
          <button className="btn-primary cursor-pointer" onClick={onClose}>
            Close & Acknowledge →
          </button>
        </div>
      </div>
    </div>
  );
};
